### ISSUE TITLE
Question about the data augmentation 

### ISSUE THREAD

**Issue by JamesYang110043** [tudelft/event_flow#7]
Dear authors, 

Firstly, I'd like to express my gratitude for your contributions to event-based optical flow research; it's truly remarkable work. I have been delving into your code, specifically the self-supervised event-based optical flow codebase, and I have a small question.

In `dataloader/h5.py` line 279 ,see below
```python
# data augmentation
xs, ys, ps = self.augment_events(xs, ys, ps, batch)
``` 

The function `augment_events()` in `dataloader/base.py` line 88, see below
```python
    def augment_events(self, xs, ys, ps, batch):
        """
        Augment event sequence with horizontal, vertical, and polarity flips.
        :return xs: [N] tensor with event x location
        :return ys: [N] tensor with event y location
        :return ps: [N] tensor with event polarity ([-1, 1])
        :param batch: batch index
        :return xs: [N] tensor with augmented event x location
        :return ys: [N] tensor with augmented event y location
        :return ps: [N] tensor with augmented event polarity ([-1, 1])
        """

        for i, mechanism in enumerate(self.config["loader"]["augment"]):

            if mechanism == "Horizontal":
                if self.batch_augmentation["Horizontal"][batch]:
                    xs = self.config["loader"]["resolution"][1] - 1 - xs

            elif mechanism == "Vertical":
                if self.batch_augmentation["Vertical"][batch]:
                    ys = self.config["loader"]["resolution"][0] - 1 - ys

            elif mechanism == "Polarity":
                if self.batch_augmentation["Polarity"][batch]:
                    ps *= -1

        return xs, ys, ps
``` 

To the best of my knowledge, when performing data augmentation, the dataset should ideally include both the original data and the augmented data. For instance, if we consider horizontal augmentation, both the original dataset and the horizontally augmented dataset should be present.

However, based on the provided code, it appears that only the original data is being utilized for horizontal, vertical, and polarity transformations. The dataset does not appear to include the augmented versions.
Can you explain it? Thanks in advance.

**Comment by Huizerd** [comment]
Hi James, thank you for the kind words! To answer your question: we indeed don't return the original and augmented data. This is because for every sequence, there's a probability that it will be augmented with one or more mechanisms. Augmentation is determined at the start of training [here](https://github.com/tudelft/event_flow/blob/e81f9630a145da8c7e57b2cfd38cf6c0b47ac14f/dataloader/base.py#L32) and then reset for every epoch [here](https://github.com/tudelft/event_flow/blob/e81f9630a145da8c7e57b2cfd38cf6c0b47ac14f/dataloader/base.py#L62). Concretely, this means that every epoch, we will have a differently augmented dataset. I hope this makes sense!

**Comment by JamesYang110043** [comment]
Thank you very much for your response. I've gained a lot from it.
